### PR TITLE
According to the readme useDirty is by default 'false'

### PR DESCRIPTION
**Pull request by htesgaard**
Change code accordingly

### CODE REVIEW

**Comment by McFoggy** [comment]
I think I prefer to change the doc instead.

**Comment by htesgaard** [comment]
@McFoggy the problem is that use dirty cannot be deactivated as it is implemented now. The boolean can not be toggled from the command line.

**Comment by McFoggy** [comment]
you can use `--useDirty=false` to deactivate it

**Comment by McFoggy** [comment]
````
12:57:26 C:\workspace\jgitver-lib>java -jar target\jgitver-0.12.1-SNAPSHOT-executable.jar
0.12.1-1-dirty
12:57:31 C:\workspace\jgitver-lib>java -jar target\jgitver-0.12.1-SNAPSHOT-executable.jar --useDirty=false
0.12.1-1
````

**Comment by htesgaard** [comment]
You are right, my bad 😢Case closed 👍

**Pull request closed without merging**
